<?php

namespace App\Enums;

enum GovernanceAuditAction: string
{
    case REQUISITION_SUBMITTED = 'REQUISITION_SUBMITTED';
    case REQUISITION_APPROVED = 'REQUISITION_APPROVED';
    case REQUISITION_REJECTED = 'REQUISITION_REJECTED';
    case REQUISITION_RESUBMITTED = 'REQUISITION_RESUBMITTED';
    case REQUISITION_OPENED = 'REQUISITION_OPENED';
    case REQUISITION_CLOSED = 'REQUISITION_CLOSED';
    case TEMPLATE_VERSION_CREATED = 'TEMPLATE_VERSION_CREATED';
    case SYNC_PUBLISHED = 'SYNC_PUBLISHED';
    case SYNC_UNPUBLISHED = 'SYNC_UNPUBLISHED';
    case DEPT_HEAD_ASSIGNED = 'DEPT_HEAD_ASSIGNED';
    case DEPT_HEAD_REMOVED = 'DEPT_HEAD_REMOVED';
}
