<?php

namespace App\Enums;

enum InterviewAuditAction: string
{
    case SCHEDULED = 'SCHEDULED';
    case RESCHEDULED = 'RESCHEDULED';
    case CANCELLED = 'CANCELLED';
    case COMPLETED = 'COMPLETED';
    case FEEDBACK_SUBMITTED = 'FEEDBACK_SUBMITTED';
    case ASSIGNMENT_RECOMMENDED = 'ASSIGNMENT_RECOMMENDED';
    case ASSIGNMENT_ACCEPTED = 'ASSIGNMENT_ACCEPTED';
    case ASSIGNMENT_CHANGED = 'ASSIGNMENT_CHANGED';
    case ASSIGNMENT_REMOVED = 'ASSIGNMENT_REMOVED';
    case ASSIGNMENT_OVERRIDE = 'ASSIGNMENT_OVERRIDE';
    case BRIEFING_CREATED = 'BRIEFING_CREATED';
    case WORKSPACE_UPDATED = 'WORKSPACE_UPDATED';
    case EXTENSION_REQUESTED = 'EXTENSION_REQUESTED';
    case EXTENSION_APPROVED = 'EXTENSION_APPROVED';
    case EXTENSION_DENIED = 'EXTENSION_DENIED';
    case EXTENSION_CANCELLED = 'EXTENSION_CANCELLED';
    case UNAUTHORIZED_ACCESS_DENIED = 'UNAUTHORIZED_ACCESS_DENIED';

    public static function values(): array
    {
        return array_map(fn (self $action): string => $action->value, self::cases());
    }
}
