<?php

namespace App\Enums;

enum ScreeningAuditAction: string {
    case CONFIG_CREATED = 'CONFIG_CREATED';
    case CONFIG_UPDATED = 'CONFIG_UPDATED';
    case SCORES_RECALCULATED = 'SCORES_RECALCULATED';
    case SHORTLIST_GENERATED = 'SHORTLIST_GENERATED';
    case TRIAGE_EXECUTED = 'TRIAGE_EXECUTED';
    case TRIAGE_STATUS_CHANGE = 'TRIAGE_STATUS_CHANGE';
    case DUPLICATE_CHECK_RUN = 'DUPLICATE_CHECK_RUN';
    case DUPLICATE_DECISION = 'DUPLICATE_DECISION';
}
